#!/bin/sh

PACKAGES=(
  "github.com/go-delve/delve/cmd/dlv"
  "golang.org/x/tools/cmd/goimports"
  "honnef.co/go/tools/cmd/staticcheck"
  "github.com/cosmtrek/air"
  "github.com/cweill/gotests/..."
)

for pkg in "${PACKAGES[@]}"; do
  eval "go install ${pkg}@latest"
done
