#!/bin/sh

if !(type multipass >/dev/null 2>&1;) then
  echo "multipass command not found"
  exit 1
fi

HOST_IP=$(multipass info docker --format json | jq -r '.info["docker"].ipv4[0]')
PORT="$1"
ENDPOINT_PATH=$(echo "$2" | sed "s/^\///")
open "http://$HOST_IP:$PORT/$ENDPOINT_PATH"
