#!/bin/sh
# shellcheck disable=1091

DOT_PATH="$HOME/dotfiles"
SH_PATH="$DOT_PATH/modules/scripts"

case "$1" in
"install") . "$DOT_PATH/install.sh" ;;
"asdf") . "$SH_PATH/asdf_setup.sh" ;;
"go") . "$SH_PATH/go_setup.sh" ;;
"node") . "$SH_PATH/node_setup.sh" ;;
"python") . "$SH_PATH/python_setup.sh" ;;
"ruby") . "$SH_PATH/ruby_setup.sh" ;;
"packages")
  . "$SH_PATH/go_setup.sh"
  . "$SH_PATH/node_setup.sh"
  . "$SH_PATH/python_setup.sh"
  . "$SH_PATH/ruby_setup.sh"
  ;;
*) echo "$1 is a unknown argument" ;;
esac
